baseurl: "/"
title: "Statistical Computing and Computation"
author: "Colin Rundel"
copyright: "&copy; 2021. All rights reserved."
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir: "docs"

menu:
  main:
  - name: Syllabus
    pre: <i class='fa fa-file-text-o fa-fw'></i>
    weight: 2
    identifier: syllabus
    url: "#syllabus"
  - name: Sakai
    pre: <i class="fas fa-chalkboard-teacher"></i>
    weight: 3
    url: https://sakai.duke.edu/portal/site/25babfb7-86b8-4d58-8158-5f8d78e44dcd
  - name: Github
    pre: <i class='fa fa-github fa-fw'></i>
    weight: 6
    url: https://github.com/sta663-sp22
  - name: RStudio
    pre: <i class='fab fa-r-project fa-fw'></i>
    weight: 7
    url: http://rstudio.stat.duke.edu:8787
  - name: Container
    pre: <i class="fab fa-docker fa-fw"></i>
    url: https://cmgr.oit.duke.edu/containers

params:
  subtitle: "(Spring 2022)"
  course: "Sta 663"
  highlightjs: androidstudio
  highlightjs_extra_languages:
    - yaml
  dateFormat: '02 Jan 2006, 15:04'
  sections:
    - schedule
    - syllabus
    - textbooks
    - about
  contact:
    - name: Dr. Colin Rundel
      office:
      email: colin.rundel@duke.edu
      hours: TBD
  assignments:
    - name: Homework
      type: Team
      value: 50%
    - name: Midterms
      value: 40%
    - name: Project
      value: 10%
